# Generated by Django 6.0.2 on 2026-02-11 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='turno',
            old_name='nombre_cliente',
            new_name='cliente',
        ),
        migrations.AddField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turnos.profesional'),
            preserve_default=False,
        ),
    ]
